/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import dao.HoaDonDao;
import entity.CTHoaDon;
import entity.HoaDon;
import service.impl.BanImp;
import service.impl.HoaDonImp;
import service.impl.KhachHangImpl;
import service.impl.NhanVienImp;
import service.impl.SanPhamImp;

/**
 *
 * @author Le Quoc Phong
 */
public class ThanhToan extends javax.swing.JFrame implements KeyListener{
    private String maBans;
    private DefaultTableModel tableModel;
    private SanPhamImp spimp = new SanPhamImp();
    private KhachHangImpl khachHangImp = new KhachHangImpl();
    private HoaDonImp hoaDonImp = new HoaDonImp();
    private BanImp banImp = new BanImp();
    private NhanVienImp nhanVienImp = new NhanVienImp();
    private HoaDonDao hdDao = new HoaDonDao();
    private String maNVTK = "";

    /**
     * Creates new form ThanhToan
     */
    public ThanhToan(String maBan, String maNVTK) {
        setSize(770, 600);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Thanh toán hóa đơn bàn " + maBan);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        maBans = maBan;
        this.maNVTK = maNVTK;
        initComponents();
        UpdataHoaDon(maBans);
    }

    private void UpdataHoaDon(String maBan) {
        tableModel.setRowCount(0);
        Locale localeEN = new Locale("en", "EN");
        NumberFormat en = NumberFormat.getInstance(localeEN);
        double tongTien = 0;
        double chietKhau = 0;
        int sl = 0;
        for (HoaDon h : hoaDonImp.getHoaDonWhereBan(maBan)) {
            double thanhTien = h.getDsCTHD().get(0).getSoLuong() * h.getDsCTHD().get(0).getSanPham().getGia();
            String[] row = { h.getDsCTHD().get(0).getSanPham().getTenSP(),
                    en.format(h.getDsCTHD().get(0).getSanPham().getGia()),
                    String.valueOf(h.getDsCTHD().get(0).getSoLuong()), en.format(thanhTien) };

            tongTien += thanhTien;

            sl += h.getDsCTHD().get(0).getSoLuong();

            txtTenKH.setText(h.getKhachHang().getTenKH());
            txtTenNV.setText(h.getNhanVien().getTenNV());
            txtSDT.setText(h.getKhachHang().getSdt());
            txtSDTNV.setText(h.getNhanVien().getSdt());
            lblNgay.setText("Ngày: " + h.getNgayLapHD());
            txtMaBan.setText(maBan);

            txtMaHD.setText(h.getMaHD());
            tableModel.addRow(row);
        }
        if (sl >= 5 && sl < 10) {// chiết khấu 5%
            chietKhau = tongTien * 0.05;
            jLabel17.setText("Chiết khấu(5%):");
            txtChietKhau.setText(en.format(chietKhau) + " VND");
        } else if (sl < 5) {
            chietKhau = 0;
        } else {
            chietKhau = tongTien * 0.1;
            jLabel17.setText("Chiết khấu(10%):");
            txtChietKhau.setText(en.format(chietKhau) + " VND");
        }
        txtTongTienPhaiTra.setText(en.format(tongTien - chietKhau) + " VND");
        
        double tienIP=0;
        if(txtTienInput.getText().equals(""))
            tienIP = 0;
        else {
            double tienKH = Double.parseDouble(txtTienInput.getText());
            double tienTraLai = (tongTien-chietKhau) -tienKH;
            txtTienOutput.setText(String.valueOf(tienTraLai));
        }
       
        
        table.setModel(tableModel);
        table.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();
        lblHotline = new javax.swing.JLabel();
        lblTieuDe = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSDTNV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtChietKhau = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTongTienPhaiTra = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTienInput = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtTienOutput = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnCencel = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        

        lblNgay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgay.setText("Ngày 2/11/2022");

        lblHotline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHotline.setText("Hotline: 19001919");

        lblTieuDe.setText("THANH TOÁN HÓA ĐƠN");

        jLabel5.setText("Tên khách hàng:");

        txtTenKH.setText("Lê Văn B");

        jLabel7.setText("Số điện thoại: ");

        txtSDT.setText("0926558875");

        jLabel9.setText("Tên nhân viên thu ngân:");

        txtTenNV.setText("Nguyễn Thị C");

        jLabel11.setText("Số điện thoại: ");

        txtSDTNV.setText("026125847");

        String[] header = { "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền" };
        tableModel = new DefaultTableModel(header, 0);

        table = new JTable(tableModel);

        jScrollPane1.setViewportView(table);

        jLabel13.setText("Mã bàn:");

        txtMaBan.setText("B01");

        jLabel15.setText("Số hóa đơn:");

        txtMaHD.setText("HD08938N");

        jLabel17.setText("Chiết khấu(%):");

        txtChietKhau.setText("0%");

        jLabel19.setText("Tổng tiền phải thanh toán:");

        txtTongTienPhaiTra.setText("15000");

        jLabel21.setText("Tiền khách đưa:");

        jLabel22.setText("Tiền phải trả lại:");

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(txtTienInput.getText().equals("") || txtTienInput.getText() == null) {
                    JOptionPane.showMessageDialog(jLabel2, "Hãy nhập số tiền nhận");
                }else {
                    double tienThua = Double.parseDouble(txtTienOutput.getText());
                    if(tienThua>=0) {
                        new ManHinhChinh(maBans,maNVTK).setVisible(true);
                        dispose();
                    }else {
                        JOptionPane.showMessageDialog(jLabel2, "Không đủ tiền thanh toán");
                    }
                }
            }
        });

        btnCencel.setText("Cencel");
        btnCencel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVisible(false);
                new ManHinhChinh(null,maNVTK).setVisible(true);
            }
        });
        txtTienInput.addKeyListener(this);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHotline, javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel5,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 93,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(txtTenKH,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 85,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(txtSDT,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 108,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(92, 92, 92)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                134, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtChietKhau,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 99,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel15,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        82,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel13,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        43,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel17))
                                                                        .addGap(75, 75, 75)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtMaBan,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        43,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txtMaHD,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        99,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jLabel19,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                145,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(txtTongTienPhaiTra,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                99,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(103, 103, 103)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel21)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(txtTienInput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        32, Short.MAX_VALUE)
                                                                .addComponent(txtTienOutput,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 102,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(97, 97, 97))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(300, 300, 300))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(btnCencel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGap(91, 91, 91)
                                                        .addComponent(btnThanhToan)
                                                        .addGap(248, 248, 248)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblNgay)
                                        .addComponent(lblHotline))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtTenKH)
                                        .addComponent(jLabel9)
                                        .addComponent(txtTenNV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtSDT)
                                        .addComponent(jLabel11)
                                        .addComponent(txtSDTNV))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(txtMaBan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(txtMaHD))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel17)
                                                        .addComponent(txtChietKhau))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel19)
                                                        .addComponent(txtTongTienPhaiTra,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41,
                                                        Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel21)
                                                        .addComponent(txtTienInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel22)
                                                        .addComponent(txtTienOutput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCencel)
                                        .addComponent(btnThanhToan))
                                .addContainerGap(22, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnThanhToanActionPerformed

    private void btnCencelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCencelActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnCencelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThanhToan(null).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnCencel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHotline;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtChietKhau;
    private javax.swing.JLabel txtMaBan;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtSDTNV;
    private javax.swing.JLabel txtTenKH;
    private javax.swing.JLabel txtTenNV;
    private javax.swing.JTextField txtTienInput;
    private javax.swing.JTextField txtTienOutput;
    private javax.swing.JLabel txtTongTienPhaiTra;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        Object obj = e.getSource();
        if(obj.equals(txtTienInput)) {
            txtTienOutput.setEditable(false);
            String tien = txtTongTienPhaiTra.getText();
            tien = tien.replace(",", "");
            tien = tien.replace(" VND", "");
            double tongTien = Double.parseDouble(tien);
            double tienNhan = 0.0;
            try {
                tienNhan = Double.parseDouble(txtTienInput.getText());
            } catch (Exception e2) {
                JOptionPane.showMessageDialog(jScrollPane1, "so tien thanh toan phai la so");
                txtTienInput.setText("");
                txtTienOutput.setText("");
            }
            txtTienOutput.setText(String.format("%.0f", tienNhan - tongTien));
        }
    }
}
